load("//bazel:cmake.bzl", "cmake_config")

cmake_config(
    name = "jconfig",
    src = "jconfig.h.in",
    out = "jconfig.h",
    variables = {
        "JPEG_LIB_VERSION": "62",
        "LIBJPEG_TURBO_VERSION": "4.0.0",
        "LIBJPEG_TURBO_VERSION_NUMBER": "4000000",
        "C_ARITH_CODING_SUPPORTED": "0",
        "D_ARITH_CODING_SUPPORTED": "0",
        "MEM_SRCDST_SUPPORTED": "1",
        "WITH_SIMD": "1",
        "BITS_IN_JSAMPLE": "8",
        "HAVE_LOCALE_H": "1",
        "HAVE_STDDEF_H": "1",
        "HAVE_STDLIB_H": "1",
        "NEED_SYS_TYPES_H": "1",
        "NEED_BSD_STRINGS": "0",
        "HAVE_UNSIGNED_CHAR": "1",
        "HAVE_UNSIGNED_SHORT": "1",
        "INCOMPLETE_TYPES_BROKEN": "0",
        "RIGHT_SHIFT_IS_UNSIGNED": "0",
        "__CHAR_UNSIGNED__": "0",
    },
)

cmake_config(
    name = "jconfigint",
    src = "jconfigint.h.in",
    out = "jconfigint.h",
    variables = {
        "inline": "0",
        "BUILD": "20190919",
        "INLINE": "__inline__ __attribute__((always_inline))",
        "PACKAGE_NAME": "mozjpeg",
        "VERSION": "4.0.0",
        "SIZE_T": "8",
        "HAVE_BUILTIN_CTZL": "1",
        "HAVE_INTRIN_H": "0",
    },
)

cc_library(
    name = "mozjpeg",
    srcs = [
        "jcapimin.c",
        "jcapistd.c",
        "jccoefct.c",
        "jccolor.c",
        "jcdctmgr.c",
        "jchuff.c",
        "jcext.c",
        "jcicc.c",
        "jcinit.c",
        "jcmainct.c",
        "jcmarker.c",
        "jcmaster.c",
        "jcomapi.c",
        "jcparam.c",
        "jcphuff.c",
        "jcprepct.c",
        "jcsample.c",
        "jctrans.c",
        "jdapimin.c",
        "jdapistd.c",
        "jdatadst.c",
        "jdatasrc.c",
        "jdcoefct.c",
        "jdcolor.c",
        "jddctmgr.c",
        "jdhuff.c",
        "jdicc.c",
        "jdinput.c",
        "jdmainct.c",
        "jdmarker.c",
        "jdmaster.c",
        "jdmerge.c",
        "jdphuff.c",
        "jdpostct.c",
        "jdsample.c",
        "jdtrans.c",
        "jerror.c",
        "jfdctflt.c",
        "jfdctfst.c",
        "jfdctint.c",
        "jidctflt.c",
        "jidctfst.c",
        "jidctint.c",
        "jidctred.c",
        "jquant1.c",
        "jquant2.c",
        "jutils.c",
        "jmemmgr.c",
        "jmemnobs.c",
    ] + glob(["*.h"]) + [
        ":jconfig",
        ":jconfigint",
    ],
    hdrs = [
        "jccolext.c",
        "jdcol565.c",
        "jdcolext.c",
        "jdmrg565.c",
        "jdmrgext.c",
        "jstdhuff.c",
    ],
    visibility = ["//visibility:public"],
)
